### ISSUE TITLE
Works only for MainWindow and not for other windows!

### ISSUE THREAD

**Issue by md3848** [source-weave/wpf-custom-window#1]
HI, thanks for this open source code,  I have a problem, this code not work for second window ( its work correctly for MainWindow )

![WPFCustomWIndow Problem](https://user-images.githubusercontent.com/17591943/107977120-dc4ed780-6fcf-11eb-93bc-7d4b3a3166ab.png)

**Comment by NikolayVasilev** [comment]
You have to set the style of the second window to be based on the SWWindowStyle as well. 

`<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:local="clr-namespace:WPFCustomWindow">

    <Style TargetType="local:MainWindow" BasedOn="{StaticResource SWWindowStyle}"/>
    <Style TargetType="local:SettingsWindow" BasedOn="{StaticResource SWWindowStyle}"/>
</ResourceDictionary>`

**Comment by md3848** [comment]
Thanks-You, My problem was solved with your help
